### ISSUE TITLE
User administration - Backend

### ISSUE THREAD

**Issue by bernard-paetzold** [bernard-paetzold/HMS-TLS-ingenious-plebs#4]
## Break down

| **Input** | **Processing** | **Output** |
| --------- | -------------- | ---------- |
|      User information     |      User information is updated          |      _Success_: Success message, log-file entry      |
|          |                |      _Failure_: Failure message, log-file entry      |
## Sub-tasks

- [ ] Ability to browse users
- [ ] Deletion of users
- [x] Editing of user information
